[toolchain]
package_manager = "Yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
superpull_program = "EDX7DLx7YwQFFMC9peZh5nDqiB4bKVpa2SpvSfwz4XUG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
