[toolchain]
package_manager = "Yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
superpull_program = "EDX7DLx7YwQFFMC9peZh5nDqiB4bKVpa2SpvSfwz4XUG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=0a1fbece-e0b6-4d09-9c6f-5679e9f2910d"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
