[toolchain]
package_manager = "Yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
superpull_program = "EDX7DLx7YwQFFMC9peZh5nDqiB4bKVpa2SpvSfwz4XUG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=637079fc-2bd4-48d5-9110-ab8c012da869"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
